name: CI/CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Auth on Docker Hub
        run: echo "Execute Docker login command"
      - name: Build Docker image
        run: echo "Build Docker image"
      - name: Push Docker image
        run: echo "Push Docker image"
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Auth on k8s cluster
        run: echo "Execute Docker login command"
      - name: Build Docker image
        run: echo "Build Docker image"
      - name: Push Docker image
        run: echo "Push Docker image"
