name: CI/CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./src/Dockerfile
          tags: |
            romanharen/fake-shop:latest
            romanharen/fake-shop:${{ github.run_number }}

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
  
      - name: Set up Oracle Cloud CLI (oci-cli)
        run: |
          # Install the OCI CLI
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install oci-cli
  
      - name: Set up OCI CLI configuration
        run: |
          mkdir -p ~/.oci
          touch ~/.oci/key.pem
          echo "-----BEGIN PRIVATE KEY-----" > ~/.oci/key.pem
          echo "${{ secrets.OCI_API_KEY }}" >> ~/.oci/key.pem
          echo "-----END PRIVATE KEY-----" >> ~/.oci/key.pem
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ secrets.OCI_USER_OCID }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
          echo "key_file=~/.oci/key.pem" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> ~/.oci/config
          echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config

      - name: Fix permissions
        run: |
          oci setup repair-file-permissions --file /home/runner/.oci/config 
          oci setup repair-file-permissions --file /home/runner/.oci/key.pem

      - name: Fetch Kubernetes config from Oracle Cloud
        run: |
          oci ce cluster create-kubeconfig --cluster-id ${{ secrets.OCI_CLUSTER_ID }} --file $HOME/.kube/config --region ${{ secrets.OCI_REGION }}
  
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.24.0'
  
      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./k8s/deployment.yml
          images: |
              romanharen/fake-shop:${{ github.run_number }}