name: CI/CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  # CI:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Source code
  #       uses: actions/checkout@v4.2.2

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
        
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ vars.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: ./src
  #         platforms: linux/amd64,linux/arm64
  #         push: true
  #         file: ./src/Dockerfile
  #         tags: |
  #           romanharen/fake-shop:latest
  #           romanharen/fake-shop:${{ github.run_number }}

  CD:
    runs-on: ubuntu-latest
    #needs: [CI]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Set up Oracle Cloud CLI (oci-cli)
        run: |
          # Install the OCI CLI
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install oci-cli
  
      - name: Set up OCI CLI configuration
        run: |
          # Configure OCI CLI using GitHub Secrets
          mkdir -p ~/.oci
          touch ~/.oci/key.pem
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ secrets.CI_USER_OCID }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }} >> ~/.oci/config
          echo "key_file=${{ secrets.OCI_API_KEY }}" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_TENANCY_OCID }}" >> ~/.oci/config
          echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config
  
      - name: Fetch Kubernetes config from Oracle Cloud
        run: |
          # Get the kubeconfig for the OKE cluster
          cat ~/.oci/config
          oci ce cluster create-kubeconfig --cluster-id ${{ secrets.OCI_CLUSTER_ID }} --file $HOME/.kube/config --region ${{ secrets.OCI_REGION }}
  
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.24.0'
  
      - name: Verify Kubernetes Cluster Connection
        run: |
          # Test connection to the Kubernetes cluster
          kubectl get nodes